### ISSUE TITLE
Xpath query does not work for some path

### ISSUE THREAD

**Issue by akillika** [simonkimi/xpath_selector#1]
The package works for queries like
`//*[@id='frmStudentTimetable']/table/tbody/tr[4]/td/table/tbody/tr[2]/td[1]/font`
but does not work for these kinds of xpath
`/html/body/table[1]/tbody/tr[3]/td[2]'`

Also tried using different formats of data.

Flutter version details:
```
[✓] Flutter (Channel stable, 2.5.1, on macOS 12.0.1 21A559 darwin-arm, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.62.3)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by simonkimi** [comment]
Because the root node is html, therefore, `/html` cannot be used for query. try `/body/table[1]/tbody/tr[3]/td[2]` instead

**Comment by akillika** [comment]
Thanks, it worked. Closing the thread
