### ISSUE TITLE
Attribute selector not working

### ISSUE THREAD

**Issue by Z6P0** [simonkimi/xpath_selector#9]
XPath `"//element/@attribute"` does not select the attribute but the element node.

**Comment by simonkimi** [comment]
For attributes, use their `.attrs` method. [Example](https://github.com/simonkimi/xpath_selector/blob/e97ed97b0135a480de4fcb4ecec2902298df8b6c/xpath_selector/example/html_example.dart#L37)

**Comment by Z6P0** [comment]
Yes but I expected the library to return the proper node. I'm not supposed to parse the query myself to test if it's an attribute or not.

**Comment by simonkimi** [comment]
In this package, attribute is not treated as an node, but string. 
This feature may be added in the future.
